# -*- coding: utf-8 -*-
"""agents.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VxTAe9IUt1zjgekhy-UlOzaGTVZnFE9h
"""

# AGENT DEFINITIONS (fetches Price AND News)
# Data Agent
data_agent = LlmAgent(
    name="Quant_Data_Agent",
    model=GeminiModel(model="gemini-2.5-flash", retry_options=retry_config),
    tools=[fetch_market_data, compute_simple_factors, fetch_news_sentiment],
    instruction="""
    You are the Data Agent.
    1. Identify the ticker.
    2. Call `fetch_market_data` (prices).
    3. Call `compute_simple_factors` (technical indicators).
    4. Call `fetch_news_sentiment` (headlines).

    5. Return a summary JSON with keys:
       - "ticker"
       - "n_days"
       - "available_factors"
       - "headlines" (List of strings)

    Do NOT output raw price data.
    """,
    output_key="data_summary"
)

# Signal Agent (analyzes Sentiment)
signal_agent = LlmAgent(
    name="Quant_Signal_Research_Agent",
    model=GeminiModel(model="gemini-2.5-flash", retry_options=retry_config),
    instruction="""
    You are the Signal Research Agent.
    Read the `data_summary`.

    Task:
    1. Analyze the sentiment of the "headlines" (Positive/Negative/Neutral).
    2. Choose ONE technical factor from "available_factors" (e.g. mom_5d).
    3. Formulate a hypothesis that combines BOTH sentiment and the technical factor.
       (e.g. "Positive news sentiment supports the 5-day momentum trend...")

    Return a JSON with keys: "chosen_factor", "sentiment_score", and "hypothesis".
    """,
    output_key="signal_spec"
)

# Reporting Agent (Remains mostly the same, just better inputs)
report_agent = LlmAgent(
    name="Quant_Reporting_Agent",
    model=GeminiModel(model="gemini-2.5-flash", retry_options=retry_config),
    tools=[local_backtest],
    instruction="""
    You are the Reporting Agent.
    1. Use `local_backtest` with the "chosen_factor".
    2. Write a research note.
    3. IMPORTANT: Include a "Sentiment Analysis" section discussing the headlines found by the Signal agent.
    """,
    output_key="final_report"
)